app/workouts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SelectField, SubmitField, TextAreaField
from wtforms.validators import DataRequired, Length, EqualTo, Email, ValidationError


class WorkoutForm(FlaskForm):
    category = SelectField('Category', choices=["Full body workout", "Legs", "ABS", "Upper body", "Cardio", "Stretching",
                                                "Yoga", "Pilates", "Mobility", "HIIT", "Rest"])
    description = TextAreaField("Description")
    submit = SubmitField("Submit")

app/workouts/__init__.py
from flask import Blueprint

bp = Blueprint('workouts', __name__)

from app.workouts import routes

app/workouts/routes.py
from datetime import datetime, date, timedelta
from flask import url_for, redirect, render_template
from app.week_func import get_week
from app.workouts import bp
from app import db
from app.models import Workout
from flask_login import login_required, current_user
from app.workouts.forms import WorkoutForm


@bp.route('/workout_plan', defaults={'date': str(date.today())}, methods=['GET', 'POST'])
@bp.route('/workout_plan/<date>', methods = ['GET', 'PUT'])
@login_required
def workout_plan(date):
    today = datetime.strptime(date, '%Y-%m-%d').date()
    tomorrow = today + timedelta(days=7)
    yesterday = today - timedelta(days=7)
    week = get_week(date)

    monday_plan = Workout.query.filter_by(user=current_user, date=week['monday']).all()
    tuesday_plan = Workout.query.filter_by(user=current_user, date=week['tuesday']).all()
    wednesday_plan = Workout.query.filter_by(user=current_user, date=week['wednesday']).all()
    thursday_plan = Workout.query.filter_by(user=current_user, date=week['thursday']).all()
    friday_plan = Workout.query.filter_by(user=current_user, date=week['friday']).all()
    saturday_plan = Workout.query.filter_by(user=current_user, date=week['saturday']).all()
    sunday_plan = Workout.query.filter_by(user=current_user, date=week['sunday']).all()

    plan = [monday_plan, tuesday_plan, wednesday_plan, thursday_plan, friday_plan, saturday_plan, sunday_plan]

    return render_template('workouts/workout_plan.html', today=today, tomorrow=tomorrow, yesterday=yesterday, week=week,
                           monday_plan=monday_plan, tuesday_plan=tuesday_plan, wednesday_plan=wednesday_plan,
                           thursday_plan=thursday_plan, friday_plan=friday_plan, saturday_plan=saturday_plan,
                           sunday_plan=sunday_plan, plan=plan)


@bp.route('/add_workout/<date>', methods=['GET', 'POST'])
@login_required
def add_workout(date):
    form = WorkoutForm()
    if form.validate_on_submit():
        new_workout = Workout(category=form.category.data, description=form.description.data,
                              user=current_user, date=datetime.strptime(date, '%Y-%m-%d').date())
        db.session.add(new_workout)
        db.session.commit()
        return redirect(url_for('workouts.workout_plan', date=date))
    return render_template('workouts/add_workout.html', form=form, date=date)


@bp.route('/delete_workout/<id>', methods=['GET', "POST"])
@login_required
def delete_workout(id):
    workout_to_delete = Workout.query.filter_by(id=id).first()
    db.session.delete(workout_to_delete)
    db.session.commit()
    return redirect(url_for('workouts.workout_plan', date=workout_to_delete.date))

app/templates/workouts/add_workout.html
{% extends 'base.html' %}
{% block app_content %}
    <h1>Add workout for {{ date }}:</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.category.label }}<br>
            {{ form.category(class='select') }}
        </p>
        <p>
            {{ form.description.label }}<br>
            {{ form.description(size=128) }}
        </p>
    <p>
        {{ form.submit }}
    </p>
    </form>
    <br>
        <a href="{{ url_for('workouts.workout_plan') }}">
            <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-left-square" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm11.5 5.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/></svg>
        </a>
{% endblock %}

app/templates/workouts/workout_plan.html
{% extends 'base.html' %}
{% block app_content %}
    <h1> {{ current_user.username }}'s workout plan:</h1><br>
    <table>
        <tr>
            <th></th>
            <th>
                Monday <br>
                {{ week['monday'] }}<br>
                {% if monday_plan %}
                {% for plan in monday_plan %}
                    <a href="{{ url_for('workouts.delete_workout', id=plan.id) }}">DELETE</a>
                {% endfor %}
                {% else %}
                    <a href="{{ url_for('workouts.add_workout', date=week['monday'])}}">ADD</a>
                {% endif %}
            </th>
            <th>
                Tuesday <br>
                {{ week['tuesday'] }}<br>
                {% if tuesday_plan %}
                {% for plan in tuesday_plan %}
                    <a href="{{ url_for('workouts.delete_workout', id=plan.id) }}">DELETE</a>
                {% endfor %}
                {% else %}
                    <a href="{{ url_for('workouts.add_workout', date=week['tuesday'])}}">ADD</a>
                {% endif %}
            </th>
            <th>
                Wednesday<br>
                {{ week['wednesday'] }}<br>
                {% if wednesday_plan %}
                {% for plan in wednesday_plan %}
                    <a href="{{ url_for('workouts.delete_workout', id=plan.id) }}">DELETE</a>
                {% endfor %}
                {% else %}
                    <a href="{{ url_for('workouts.add_workout', date=week['wednesday'])}}">ADD</a>
                {% endif %}
            </th>
            <th>Thursday<br>
                {{ week['thursday'] }}<br>
                {% if thursday_plan %}
                {% for plan in thursday_plan %}
                    <a href="{{ url_for('workouts.delete_workout', id=plan.id) }}">DELETE</a>
                {% endfor %}
                {% else %}
                    <a href="{{ url_for('workouts.add_workout', date=week['thursday'])}}">ADD</a>
                {% endif %}
            </th>
            <th>Friday<br>
                {{ week['friday'] }}<br>
                {% if friday_plan %}
                {% for plan in friday_plan %}
                    <a href="{{ url_for('workouts.delete_workout', id=plan.id) }}">DELETE</a>
                {% endfor %}
                {% else %}
                    <a href="{{ url_for('workouts.add_workout', date=week['friday'])}}">ADD</a>
                {% endif %}
            </th>
            <th>Saturday<br>
                {{ week['saturday'] }}<br>
                {% if saturday_plan %}
                {% for plan in saturday_plan %}
                    <a href="{{ url_for('workouts.delete_workout', id=plan.id) }}">DELETE</a>
                {% endfor %}
                {% else %}
                    <a href="{{ url_for('workouts.add_workout', date=week['saturday'])}}">ADD</a>
                {% endif %}
            </th>
            <th>Sunday<br>
                {{ week['sunday'] }}<br>
                {% if sunday_plan %}
                {% for plan in sunday_plan %}
                    <a href="{{ url_for('workouts.delete_workout', id=plan.id) }}">DELETE</a>
                {% endfor %}
                {% else %}
                    <a href="{{ url_for('workouts.add_workout', date=week['sunday'])}}">ADD</a>
                {% endif %}
            </th>
        </tr>
    <tr>
    <th>
         Category
    </th>
        <td>
            {% for plan in monday_plan %}
            {{ plan.category }}
            {% endfor %}
        </td>
        <td>
            {% for plan in tuesday_plan %}
            {{ plan.category }}
            {% endfor %}
        </td>
        <td>
            {% for plan in wednesday_plan %}
            {{ plan.category }}
            {% endfor %}
        </td>
        <td>
            {% for plan in thursday_plan %}
            {{ plan.category }}
            {% endfor %}
        </td>
        <td>
            {% for plan in friday_plan %}
            {{ plan.category }}
            {% endfor %}
        </td>
        <td>
            {% for plan in saturday_plan %}
            {{ plan.category }}
            {% endfor %}
        </td>
        <td>
            {% for plan in sunday_plan %}
            {{ plan.category }}
            {% endfor %}
        </td>
    </tr>
    <tr>
         <th>
           Description
        </th>
         <td>
            {% for plan in monday_plan %}
            {{ plan.description }}
            {% endfor %}
        </td>
         <td>
            {% for plan in tuesday_plan %}
            {{ plan.description }}
            {% endfor %}
        </td>
         <td>
            {% for plan in wednesday_plan %}
            {{ plan.description }}
            {% endfor %}
        </td>
         <td>
            {% for plan in thursday_plan %}
            {{ plan.description }}
            {% endfor %}
        </td>
         <td>
            {% for plan in friday_plan %}
            {{ plan.description }}
            {% endfor %}
        </td>
         <td>
            {% for plan in saturday_plan %}
            {{ plan.description }}
            {% endfor %}
        </td>
         <td>
            {% for plan in sunday_plan %}
            {{ plan.description }}
            {% endfor %}
        </td>
    </tr>

</table>



    <nav aria-label="...">
        <ul class="pager">
            <li class="previous">
                <a style="color: rgb(127,196,196);" href="{{ url_for('workouts.workout_plan', date=yesterday) }}">
                    <span aria-hidden="true"> &larr;</span> Last week
                </a>
            </li>
            <li class="next">
                <a style="color: rgb(127,196,196);" href="{{url_for('workouts.workout_plan', date=tomorrow)}}"> Next week
                    <span aria-hidden="true">&rarr;</span>
                </a>
            </li>
        </ul>
    </nav>
{% endblock %}