app/list/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField
from wtforms.validators import DataRequired


class ListForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Create List')


class ListProductForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    quantity = IntegerField('Quantity')
    submit = SubmitField('Add product')

app/shopping/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, IntegerField, SubmitField, SelectField, FieldList
from wtforms.fields.html5 import DateField
from wtforms.validators import DataRequired, Optional


class ListForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    submit = SubmitField('Create')


class ListProductForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    quantity = IntegerField('Quantity', validators=[Optional()])
    submit = SubmitField('Add')


class FridgeForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    quantity = IntegerField('Quantity', validators=[Optional()])
    expired_date = DateField('Expiration date',validators=[Optional()], format='%Y-%m-%d')
    category = SelectField('Category', choices=['Grains', 'Vegetables', 'Fruits', 'Dairy', 'Meat', 'Drinks'])
    submit = SubmitField('Add product')


class MenuForm(FlaskForm):
    name = StringField('Name:', validators=[DataRequired()])
    products = StringField('Products:', validators=[DataRequired()])
    category = SelectField('Category', choices=['Breakfast', 'Second breakfast', 'Lunch', 'Dessert', 'Dinner'])
    submit = SubmitField('Submit')

app/list/routes.py
from flask import url_for, redirect, render_template, flash
from sqlalchemy import desc

from app.list import bp
from app import db
from app.models import List, ListProduct
from flask_login import login_required, current_user
from app.list.forms import ListForm, ListProductForm


@login_required
@bp.route('/list', methods=['GET', 'POST'])
def list():
    lists = List.query.filter_by(user_id=current_user.id).all()
    form = ListForm()
    if form.validate_on_submit():
        list = List(name=form.name.data,user_id=current_user.id)
        db.session.add(list)
        db.session.commit()
        return redirect(url_for('list.list'))
    return render_template('list/list.html', form=form, lists=lists)


@login_required
@bp.route('/list/<id>', methods=['GET', 'POST'])
def view_list(id):
    list = List.query.filter_by(id=id).first_or_404()
    form = ListProductForm()
    if form.validate_on_submit():
        new_product = ListProduct(name=form.name.data, quantity=form.quantity.data, list_id=id, status=True)
        db.session.add(new_product)
        db.session.commit()
        return redirect(url_for('list.view_list', id=list.id))
    products = ListProduct.query.filter_by(list_id=id).order_by(desc('status'))
    return render_template('list/view_list.html', products=products, form=form, list=list)


@login_required
@bp.route('/delete/product/<id>', methods=['GET', 'POST'])
def delete_product(id):
    product = ListProduct.query.filter_by(id=id).first_or_404()
    db.session.delete(product)
    db.session.commit()
    return redirect(url_for('list.view_list', id=product.list_id))


@login_required
@bp.route('/bought/product/<id>', methods=['GET', 'POST'])
def move_to_bought(id):
    product = ListProduct.query.filter_by(id=id).first_or_404()
    if product.status:
        product.status = False
        db.session.commit()
    else:
        product.status = True
        db.session.commit()
    return redirect(url_for('list.view_list', id=product.list_id))


@login_required
@bp.route('/delete/list/<id>', methods=['GET', 'POST'])
def delete_list(id):
    list = List.query.filter_by(id=id).first_or_404()
    db.session.delete(list)
    db.session.commit()
    return redirect(url_for('list.list', id=id))

app/shopping/__init__.py
from flask import Blueprint

bp = Blueprint('shopping', __name__)

from app.shopping import routes

app/shopping/routes.py
from collections import defaultdict
from datetime import datetime, date, timedelta
from flask import url_for, redirect, render_template
from sqlalchemy import desc
from app.shopping import bp
from app import db
from app.models import List, ListProduct, Fridge, Menu
from flask_login import login_required, current_user
from app.shopping.forms import ListForm, ListProductForm, FridgeForm, MenuForm
from app.week_func import get_week
from app.food.routes import redirect_url



@bp.route('/list ', methods=['GET', 'POST'])
@login_required
def list():
    lists = List.query.filter_by(user=current_user).all()
    form = ListForm()
    if form.validate_on_submit():
        list = List(name=form.name.data, user=current_user)
        db.session.add(list)
        db.session.commit()
        return redirect(url_for('shopping.list'))
    return render_template('shopping/list.html', form=form, lists=lists)


@bp.route('/list/<id>', methods=['GET', 'POST'])
@login_required
def view_list(id):
    list = List.query.filter_by(id=id).first_or_404()
    form = ListProductForm()
    if form.validate_on_submit():
        new_product = ListProduct(name=form.name.data.capitalize(), quantity=form.quantity.data, list=list, status=True)
        db.session.add(new_product)
        db.session.commit()
        return redirect(url_for('shopping.view_list', id=list.id))
    products = ListProduct.query.filter_by(list_id=id).order_by(desc('status'))
    return render_template('shopping/view_list.html', products=products, form=form, list=list)


@bp.route('/delete/product/<id>', methods=['GET', 'POST'])
@login_required
def delete_product(id):
    product = ListProduct.query.filter_by(id=id).first_or_404()
    db.session.delete(product)
    db.session.commit()
    return redirect(url_for('shopping.view_list', id=product.list_id))


@bp.route('/bought/product/<id>', methods=['GET', 'POST'])
@login_required
def move_to_bought(id):
    product = ListProduct.query.filter_by(id=id).first_or_404()
    if product.status:
        product.status = False
        db.session.commit()
    else:
        product.status = True
        db.session.commit()
    return redirect(url_for('shopping.view_list', id=product.list_id))


@bp.route('/delete/list/<id>', methods=['GET', 'POST'])
@login_required
def delete_list(id):
    list = List.query.filter_by(id=id).first_or_404()
    db.session.delete(list)
    db.session.commit()
    return redirect(url_for('shopping.list', id=id))


@bp.route('/fridge', methods=['GET', 'POST'])
@login_required
def fridge():
    form = FridgeForm()
    now = datetime.today().date()
    if form.validate_on_submit():
        product = Fridge(name=form.name.data.capitalize(), quantity=form.quantity.data,
                         expired_date=form.expired_date.data, category=form.category.data, user=current_user)
        db.session.add(product)
        db.session.commit()
        return redirect(url_for('shopping.fridge'))
    products = Fridge.query.filter_by(user=current_user).order_by('expired_date').all()
    return render_template('shopping/fridge.html', form=form, products=products, now=now)


@bp.route('/delete/fridge_product/<id>', methods=['GET', 'POST'])
@login_required
def delete_product_from_fridge(id):
    product = Fridge.query.filter_by(id=id).first_or_404()
    db.session.delete(product)
    db.session.commit()
    return redirect(url_for('shopping.fridge'))


@bp.route('/week_menu', defaults={'date': str(date.today())}, methods=['GET', 'POST'])
@bp.route('/week_menu/<date>', methods=['GET', 'POST'])
@login_required
def week_menu(date):
    today = datetime.strptime(date, '%Y-%m-%d').date()
    tomorrow = today + timedelta(days=7)
    yesterday = today - timedelta(days=7)

    week = get_week(date)

    menu_monday = Menu.query.filter_by(date=week['monday']).all()
    menu_tuesday = Menu.query.filter_by(date=week['tuesday']).all()
    menu_wednesday = Menu.query.filter_by(date=week['wednesday']).all()
    menu_thursday = Menu.query.filter_by(date=week['thursday']).all()
    menu_friday = Menu.query.filter_by(date=week['friday']).all()
    menu_sunday = Menu.query.filter_by(date=week['sunday']).all()
    menu_saturday = Menu.query.filter_by(date=week['saturday']).all()

    return render_template('shopping/week_menu.html', menu_monday=menu_monday, menu_tuesday=menu_tuesday,
                           menu_wednesday=menu_wednesday, menu_thursday=menu_thursday, menu_friday=menu_friday,
                           menu_saturday=menu_saturday, menu_sunday=menu_sunday, week=week,
                           today=today, yesterday=yesterday, tomorrow=tomorrow)


@bp.route('/daily_menu/<day>', methods=['GET', 'POST'])
@login_required
def daily_menu(day):
    date = day

    form = MenuForm()
    if form.validate_on_submit():
        name = form.name.data
        products = form.products.data
        category = form.category.data
        dish = Menu(name=name, products=products, date=datetime.strptime(day, '%Y-%m-%d').date(),
                    category=category, user=current_user)
        db.session.add(dish)
        db.session.commit()
        return redirect(url_for('shopping.daily_menu', day=dish.date))

    dishes = Menu.query.filter_by(date=day).all()

    in_fridge = defaultdict(list, {k: [] for k in ('Breakfast', 'Second breakfast', 'Lunch', 'Dessert', 'Dinner')})
    must_buy = defaultdict(list, {k: [] for k in ('Breakfast', 'Second breakfast', 'Lunch', 'Dessert', 'Dinner')})

    for dish in dishes:
        for product in dish.products.split(','):
            check_fridge = Fridge.query.filter_by(name=product.capitalize(), user=current_user).all()
            if check_fridge:
                in_fridge[dish.category].append(product)
            else:
                must_buy[dish.category].append(product)
    return render_template('shopping/daily_menu.html', form=form, dishes=dishes, date=date, in_fridge=in_fridge,
                           must_buy=must_buy)


@bp.route('/delete/menu/<id>', methods=['GET', "POST"])
@login_required
def delete_menu(id):
    id = Menu.query.filter_by(id=id).first()
    db.session.delete(id)
    db.session.commit()
    return redirect(redirect_url())

app/templates/shopping/fridge.html
{% extends 'base.html' %}
{% block app_content %}

<h1>Add products to fridge:</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.category.label }}<br>
            {{ form.category(class='select') }}
        </p>
        <p>
            {{ form.expired_date.label }}<br>
            {{ form.expired_date(class='select') }}
        </p>
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}
        </p>
        <p>
            {{ form.quantity.label }}<br>
            {{ form.quantity(size=32) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>

    <table>
        <tr>
            <th><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-card-heading" viewBox="0 0 16 16">
  <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
  <path d="M3 8.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0-5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-1z"/>
</svg></th>
            <th><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-123" viewBox="0 0 16 16">
  <path d="M2.873 11.297V4.142H1.699L0 5.379v1.137l1.64-1.18h.06v5.961h1.174Zm3.213-5.09v-.063c0-.618.44-1.169 1.196-1.169.676 0 1.174.44 1.174 1.106 0 .624-.42 1.101-.807 1.526L4.99 10.553v.744h4.78v-.99H6.643v-.069L8.41 8.252c.65-.724 1.237-1.332 1.237-2.27C9.646 4.849 8.723 4 7.308 4c-1.573 0-2.36 1.064-2.36 2.15v.057h1.138Zm6.559 1.883h.786c.823 0 1.374.481 1.379 1.179.01.707-.55 1.216-1.421 1.21-.77-.005-1.326-.419-1.379-.953h-1.095c.042 1.053.938 1.918 2.464 1.918 1.478 0 2.642-.839 2.62-2.144-.02-1.143-.922-1.651-1.551-1.714v-.063c.535-.09 1.347-.66 1.326-1.678-.026-1.053-.933-1.855-2.359-1.845-1.5.005-2.317.88-2.348 1.898h1.116c.032-.498.498-.944 1.206-.944.703 0 1.206.435 1.206 1.07.005.64-.504 1.106-1.2 1.106h-.75v.96Z"/>
</svg></th>
            <th><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-calendar-x" viewBox="0 0 16 16">
  <path d="M6.146 7.146a.5.5 0 0 1 .708 0L8 8.293l1.146-1.147a.5.5 0 1 1 .708.708L8.707 9l1.147 1.146a.5.5 0 0 1-.708.708L8 9.707l-1.146 1.147a.5.5 0 0 1-.708-.708L7.293 9 6.146 7.854a.5.5 0 0 1 0-.708z"/>
  <path d="M3.5 0a.5.5 0 0 1 .5.5V1h8V.5a.5.5 0 0 1 1 0V1h1a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V3a2 2 0 0 1 2-2h1V.5a.5.5 0 0 1 .5-.5zM1 4v10a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V4H1z"/>
</svg></th>
            <th><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-egg-fried" viewBox="0 0 16 16">
  <path d="M8 11a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
  <path d="M13.997 5.17a5 5 0 0 0-8.101-4.09A5 5 0 0 0 1.28 9.342a5 5 0 0 0 8.336 5.109 3.5 3.5 0 0 0 5.201-4.065 3.001 3.001 0 0 0-.822-5.216zm-1-.034a1 1 0 0 0 .668.977 2.001 2.001 0 0 1 .547 3.478 1 1 0 0 0-.341 1.113 2.5 2.5 0 0 1-3.715 2.905 1 1 0 0 0-1.262.152 4 4 0 0 1-6.67-4.087 1 1 0 0 0-.2-1 4 4 0 0 1 3.693-6.61 1 1 0 0 0 .8-.2 4 4 0 0 1 6.48 3.273z"/>
</svg></th>
            <th><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
</svg></th>
        </tr>
        {% for product in products %}
            <tr>
                <td>{{ product.name }}</td>
                {% if product.quantity %}
                    <td>{{ product.quantity }}</td>
                {% else %}
                    <td> </td>
                {% endif %}
                {% if product.expired_date and product.expired_date > now%}
                    <td>{{ product.expired_date }}</td>
                    {% elif product.expired_date  and  product.expired_date <= now %}
                    <td style="color: red">{{ product.expired_date }}</td>
                {% else %}
                    <td> </td>
                {% endif %}
               <td>{{ product.category }}</td>
               <td>
                   <form action="{{ url_for('shopping.delete_product_from_fridge', id=product.id) }}">
                       <input type="submit" value="X" id="check" />
                   </form>
               </td>
               </tr>
        {% endfor %}
    </table>
    <br>
{% endblock %}

app/templates/shopping/list.html
{% extends 'base.html' %}
{% block app_content %}
    <h1>Create new list:</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>
    <br>
    <h1>My lists:</h1>
    {% for list in lists %}
        <h3>
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="RGB(132,152,182)" class="bi bi-cart4" viewBox="0 0 16 16">
            <path d="M0 2.5A.5.5 0 0 1 .5 2H2a.5.5 0 0 1 .485.379L2.89 4H14.5a.5.5 0 0 1 .485.621l-1.5 6A.5.5 0 0 1 13 11H4a.5.5 0 0 1-.485-.379L1.61 3H.5a.5.5 0 0 1-.5-.5zM3.14 5l.5 2H5V5H3.14zM6 5v2h2V5H6zm3 0v2h2V5H9zm3 0v2h1.36l.5-2H12zm1.11 3H12v2h.61l.5-2zM11 8H9v2h2V8zM8 8H6v2h2V8zM5 8H3.89l.5 2H5V8zm0 5a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0zm9-1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm-2 1a2 2 0 1 1 4 0 2 2 0 0 1-4 0z"/>
            </svg>
            <a href="{{ url_for('shopping.view_list', id=list.id) }}"> {{ list.name }}</a>
        </h3>
    {% endfor %}
{% endblock %}

app/templates/shopping/view_list.html
{% extends 'base.html' %}
{% block app_content %}
    <h1>Add product to {{ list.name }} list</h1>
    <form action="" method="post">
        {{ form.hidden_tag() }}
        <p>
            {{ form.name.label }}<br>
            {{ form.name(size=32) }}
        </p>
        <p>
            {{ form.quantity.label }}<br>
            {{ form.quantity(size=32) }}
        </p>
        <p>{{ form.submit() }}</p>
    </form>

       <table>
          <tr>
              <th><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-card-heading" viewBox="0 0 16 16">
  <path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z"/>
  <path d="M3 8.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zm0 2a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5zm0-5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-9a.5.5 0 0 1-.5-.5v-1z"/>
</svg></th>
              <th><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-123" viewBox="0 0 16 16">
  <path d="M2.873 11.297V4.142H1.699L0 5.379v1.137l1.64-1.18h.06v5.961h1.174Zm3.213-5.09v-.063c0-.618.44-1.169 1.196-1.169.676 0 1.174.44 1.174 1.106 0 .624-.42 1.101-.807 1.526L4.99 10.553v.744h4.78v-.99H6.643v-.069L8.41 8.252c.65-.724 1.237-1.332 1.237-2.27C9.646 4.849 8.723 4 7.308 4c-1.573 0-2.36 1.064-2.36 2.15v.057h1.138Zm6.559 1.883h.786c.823 0 1.374.481 1.379 1.179.01.707-.55 1.216-1.421 1.21-.77-.005-1.326-.419-1.379-.953h-1.095c.042 1.053.938 1.918 2.464 1.918 1.478 0 2.642-.839 2.62-2.144-.02-1.143-.922-1.651-1.551-1.714v-.063c.535-.09 1.347-.66 1.326-1.678-.026-1.053-.933-1.855-2.359-1.845-1.5.005-2.317.88-2.348 1.898h1.116c.032-.498.498-.944 1.206-.944.703 0 1.206.435 1.206 1.07.005.64-.504 1.106-1.2 1.106h-.75v.96Z"/>
</svg></th>
              <th><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-cart-check" viewBox="0 0 16 16">
  <path d="M11.354 6.354a.5.5 0 0 0-.708-.708L8 8.293 6.854 7.146a.5.5 0 1 0-.708.708l1.5 1.5a.5.5 0 0 0 .708 0l3-3z"/>
  <path d="M.5 1a.5.5 0 0 0 0 1h1.11l.401 1.607 1.498 7.985A.5.5 0 0 0 4 12h1a2 2 0 1 0 0 4 2 2 0 0 0 0-4h7a2 2 0 1 0 0 4 2 2 0 0 0 0-4h1a.5.5 0 0 0 .491-.408l1.5-8A.5.5 0 0 0 14.5 3H2.89l-.405-1.621A.5.5 0 0 0 2 1H.5zm3.915 10L3.102 4h10.796l-1.313 7h-8.17zM6 14a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm7 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
</svg></th>
              <th><svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-trash" viewBox="0 0 16 16">
  <path d="M5.5 5.5A.5.5 0 0 1 6 6v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm2.5 0a.5.5 0 0 1 .5.5v6a.5.5 0 0 1-1 0V6a.5.5 0 0 1 .5-.5zm3 .5a.5.5 0 0 0-1 0v6a.5.5 0 0 0 1 0V6z"/>
  <path fill-rule="evenodd" d="M14.5 3a1 1 0 0 1-1 1H13v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V4h-.5a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1H6a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1h3.5a1 1 0 0 1 1 1v1zM4.118 4 4 4.059V13a1 1 0 0 0 1 1h6a1 1 0 0 0 1-1V4.059L11.882 4H4.118zM2.5 3V2h11v1h-11z"/>
</svg></th>
          </tr>
           {% for product in products %}
               {% if product.status==True %}
               <tr>
               <td>{{ product.name }}</td>
                   {% if product.quantity %}
               <td>{{ product.quantity }}</td>
                       {% else %}
                       <td> </td>
                       {% endif %}
               <td>
                   <form action="{{ url_for('shopping.move_to_bought', id=product.id) }}">
                       <input type="submit" value="" id="check"/>
                   </form>
               </td>
               <td>
                   <form action="{{ url_for('shopping.delete_product', id=product.id) }}">
                       <input type="submit" value="X" id="check" />
                   </form>
               </td>
               </tr>
               {% else %}
               <tr class="strikeout">
               <td>{{ product.name }}</td>
               <td>{{ product.quantity }}</td>
               <td>
                   <form action="{{ url_for('shopping.move_to_bought', id=product.id) }}">
                       <input type="submit" value="" id="bought"/>
                   </form>
               </td>
               <td>
                   <form action="{{ url_for('shopping.delete_product', id=product.id) }}">
                       <input type="submit" value="X" id="check" />
                   </form>
               </td>
               </tr>
               {% endif %}
           {% endfor %}
       </table>
    <br>
    <a href="{{ url_for('shopping.delete_list', id=list.id) }}"> Delete this list</a><br><br>
    <a href="{{ url_for('shopping.list') }}">
    <svg xmlns="http://www.w3.org/2000/svg" width="30" height="30" fill="currentColor" class="bi bi-arrow-left-square" viewBox="0 0 16 16">
    <path fill-rule="evenodd" d="M15 2a1 1 0 0 0-1-1H2a1 1 0 0 0-1 1v12a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1V2zM0 2a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2zm11.5 5.5a.5.5 0 0 1 0 1H5.707l2.147 2.146a.5.5 0 0 1-.708.708l-3-3a.5.5 0 0 1 0-.708l3-3a.5.5 0 1 1 .708.708L5.707 7.5H11.5z"/></svg>
    </a>

{% endblock %}